actions:
  - procedure: aur.install
    info: Installing fastfetch
    packages: ["fastfetch"]
    skip_condition: "fastfetch -V"

  - procedure: os.symlink
    info: Adding symlink for fastfetch styles
    src: "./files/style"
    dst: "{{ user.home }}/.local/share/fastfetch"

  - procedure: os.symlink
    info: Adding symlink for fastfetch configs
    src: "./files/configs"
    dst: "{{ user.home }}/.config/fastfetch"
