actions:
  - procedure: os.remove
    info: Removing old pacman.conf backup
    src: "/etc/pacman.conf.bak"
    not_exists_ok: true
    privileged: true

  - procedure: os.move
    info: "Backupping old pacman.conf"
    src: "/etc/pacman.conf"
    dst: "/etc/pacman.conf.bak"
    privileged: true

  - procedure: os.symlink
    info: "Adding symlink for pacman.conf"
    src: "./files/pacman.conf"
    dst: "/etc/pacman.conf"
    privileged: true

  - procedure: aur.update
    info: "Updating system"
