actions:
  - procedure: aur.install
    info: Installing zsh
    packages: ["zsh", "zsh-completions"]

  - procedure: aur.install
    info: Installing Nerd Fonts
    packages: ["nerd-fonts"]

  - procedure: aur.install
    info: Installing startship
    packages: ["starship"]
    skip_condition: starship -V

  - procedure: os.symlink
    info: Adding symlink for starship config
    src: "./files/starship.toml"
    dst: "{{ user.home }}/.config/starship.toml"

  - procedure: os.symlink
    info: Adding symlink to zsh config
    src: "./files/.zshrc"
    dst: "{{ user.home }}/.zshrc"

  - procedure: shell.run
    info: Changing shell for user
    command: chsh
    args: ["-s", "$(which zsh)"]
